### ISSUE TITLE
503 Error

### ISSUE THREAD

**Issue by xPiston** [dilan-dio4/Snow#3]
### Hello,

I get an error when I try to validate a litecoin transaction

This is the error: [error.log](https://github.com/dilan-dio4/Keagate/files/9170362/error.log)

I tried to do local transactions with the same configuration and everything works fine

### System informations
EC2 instance with no particular specifications

**Comment by dilan-dio4** [comment]
Hello @xPiston. Currently investigating...

Did you copy the same config/local.json file to your remote machine?

**Comment by xPiston** [comment]
Yes my config is identical, I copied the default file and the local file

**Comment by dilan-dio4** [comment]
Okay, give me one second here. Im currently add a few fail-checks in the backend package where tx data is gathered.

**Comment by dilan-dio4** [comment]
Try reinstalling Keagate deps now and restart server, in the root Keagate/ folder do:

```
pnpm run clean
pnpm i
pnpm run build
pnpm run start
```

**Comment by xPiston** [comment]
Hello,

After moving the application to another instance, everything works correctly.

Thank you for taking the time to help me

**Comment by dilan-dio4** [comment]
👌
